### ISSUE TITLE
item里面的RecyclerView的位置会重置

### ISSUE THREAD

**Issue by e-hai** [z593492734/nesting-recylcerview#2]
父RecyclerView滑动后，item里面的RecyclerView的位置会重置

**Comment by z593492734** [comment]
是的，RecyclerView自带的回收机制会在条目离开屏幕之后将条目回收，如果重新出现则需要重新加载。所以在RecyclerView的条目里运用某些不希望重置的功能比如轮播图、倒计时等，需要在条目回收的时候单独创建成员变量来保存状态值，在下次加载的时候取出状态值。
使用RecyclerView的优势就在于节省内存，所以如果禁用RecyclerView的自动回收机制，那么违背我们的使用RecyclerView的初衷。

**Comment by YuanTiger** [comment]
是的，RecyclerView自带的回收机制会在条目离开屏幕之后将条目回收，如果重新出现则需要重新加载。所以在RecyclerView的条目里运用某些不希望重置的功能比如轮播图、倒计时等，需要在条目回收的时候单独创建成员变量来保存状态值，在下次加载的时候取出状态值。
使用RecyclerView的优势就在于节省内存，所以如果禁用RecyclerView的自动回收机制，那么违背我们的使用RecyclerView的初衷。

**Comment by YuanTiger** [comment]
点错了。。把问题close了。。。

**Comment by e-hai** [comment]
嗯嗯，原来这样，我也想实现记录滑动到的状态值，但是怎么监听到该item被销毁呢，我的adapter有很多ItemViewType，实在不知道怎么记录好

**Comment by YuanTiger** [comment]
RecyclerView.Adapter中有2个方法可以重写：
**onViewAttachedToWindow(BaseHolder holder)**当条目加载时调用
**onViewDetachedFromWindow(BaseHolder holder)**当条目回收时调用
我简单实现了状态保存的做法，你可以拉取我最新的代码看一下。

**Comment by e-hai** [comment]
嗯嗯，我拜读一下

**Comment by e-hai** [comment]
adapter一定要在onBindViewHolder每次都创建一次吗？会不会很耗性能

**Comment by e-hai** [comment]
还是有个比较重要的问题，子RecyclerView左右滑动的容易触发父RecyclerView的上下滑动

**Comment by YuanTiger** [comment]
滑动冲突的问题我刚试了试，只要水平到达某个方向的尽头，但是继续往那个方向滑动的话，子RecyclerView就无法响应。其他时机没有明显的滑动冲突啊。
关于子View的初始化，因为RecyclerView的回收机制，所以子View重复的创建是肯定的。那么如果将子Adapter的存活周期延长到和父RecyclerView一样，应该可以像你说的，减少创建时的耗时，增加滑动的流畅度。但是无疑也增加了当前Activity的变量的数量，同样会对内存造成压力。这样的话，各有利弊吧！而且以上都是猜测，我瞎说的。。哈哈哈

**Comment by e-hai** [comment]
设置不同高度的子RecyclerView的时候，滑动时子RecyclerView的item的高度会错乱呢

**Comment by YuanTiger** [comment]
这个问题我没有出现过呢，可以给我发份你的demo吗？

**Comment by e-hai** [comment]
抱歉，现在才看到，这个问题我已经解决了，是由于我的需求是根据item里的内容来改变item的高度，是由于我在apdater中使用了变量来记录高度，所以才会错乱。最后我在数据集中添加了高度的变量来记录，解决了这个问题了，非常感谢你的回答
